name: fechamento-caixa
static_sites:
  - name: web
    github:
      branch: main
      deploy_on_push: true
      repo: rodrigssousa-sudo/fechamento-caixa
    source_dir: /
    index_document: index.html
    catchall_document: index.html
    routes:
      - path: /
