name: fechamento-caixa

static_sites:
  - name: web
    github:
      repo: rodrigssousa-sudo/fechamento-caixa
      branch: main
      deploy_on_push: true

    source_dir: /
    index_document: index.html
    catchall_document: index.html

    routes:
      - path: /
